
project_id = "llkyifjrskvqvyjnsnqy"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[[functions]]
name = "verify-razorpay-payment"
verify_jwt = true

[[functions]]
name = "get-organization-projects"
verify_jwt = true
